# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac90fbf2d4cb6c0115c5661bb9aa9ecea6aa84fad9594ee460613c51ace3f9e58f9d122a24f2dd767c65ace606355b93562073050ac2b7f6b34cb1ef4ee4a671

test:
  secret_key_base: aef0f180948665c44884d3ba481c0e782db080de47ef5c85162180fcddc6a56653a1f009fe039c66f09e89124464b8a8e9c01328763e650f23accf3d903924fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
